About/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AboutUsView, FAQView, about


app_name = 'about'

router = DefaultRouter()
router.register(r'about-us', AboutUsView, basename='about-us')
router.register(r'FAQ', FAQView, basename='faq')


urlpatterns = [
    path('', about, name='about-view'),  # صفحه اصلی
    path('api/', include(router.urls)),
]

Blog/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'blogs'

router = DefaultRouter()
router.register(r'blog', BlogPostViewSet, basename='blog')

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog-view'),  # صفحه اصلی
    path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),

    path('api/', include(router.urls)),

]

Contact/urls.py
from django.urls import path
from . import views
from .views import EmailView

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact-view'),  # صفحه اصلی
    path('api/', EmailView.as_view(), name='email'),

]

Home/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'content', views.ContentView, basename='content')
router.register(r'vision', views.VisionView, basename='vision')
router.register(r'features', views.FeaturesView, basename='features')


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home-view'),  # صفحه اصلی
    path('api/', include(router.urls)),
]

Product/urls.py
from django.urls import path, include
from .views import products, ProductView, FeaturesView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'product', ProductView, basename='product')
router.register(r'features', FeaturesView, basename='features')


app_name = 'products'

urlpatterns = [
    path('<int:pk>/', products, name='product-view'),  # صفحه اصلی
    path('api/', include(router.urls)),
]

Seo/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

from .views import test_path

router = DefaultRouter()
router.register(r'seo', views.SEOPageView, basename='seo')
router.register(r'keyword', views.KeywordView, basename='keyword')

app_name = 'seo'

urlpatterns = [
    path('api/', include(router.urls)),
    path('test-path/', test_path, name='test_path'),

]

User/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    get_or_create_temporary_user,
    log_user_activity,
    log_exit_time, login_view, register_view, RegisterView, UserListView, UserDetailView, custom_login,
)


# Customize the router to use 'number' as the lookup field
class CustomRouter(DefaultRouter):
    def get_urls(self):
        urls = super().get_urls()
        for url in urls:
            # Access the URL pattern string using the `pattern` property
            pattern = str(url.pattern)
            if '{pk}' in pattern:
                # Replace '{pk}' with '{number}' in the URL pattern
                url.pattern._regex = url.pattern._regex.replace('{pk}', '{number}')
        return urls


app_name = "user"

urlpatterns = [
    path("api/users/create-temporary/", get_or_create_temporary_user, name="create_temporary_user"),
    path("api/users/log-activity/", log_user_activity, name="log_activity"),
    path("api/users/log-exit/", log_exit_time, name="log_exit_time"),
    path("login/", login_view, name="login_view"),
    path("register/", register_view, name="register_view"),
    path("api/register/", RegisterView.as_view(), name="register"),
    path('api/login/', custom_login, name='login'),
    path("api/users/", UserListView.as_view(), name="user-list"),
    path("api/users/<uuid:id>/", UserDetailView.as_view(), name="user-detail"),

]

WebMail/urls.py
# urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter


from . import views
from .views import MailAccountViewSet

app_name = "webmail"

router = DefaultRouter()
router.register(r"accounts", MailAccountViewSet, basename="account")

urlpatterns = [
    # صفحه HTML Inbox
    path("inbox/", views.inbox_view, name="inbox_view"),

    # API endpoints (برای fetch از جاوا اسکریپت)
    path("api/inbox/", views.inbox_api, name="inbox_api"),                 # GET -> JSON list
    path("api/email/<str:uid>/", views.fetch_email_view, name="fetch_email"),  # GET -> single email JSON
    path("api/send/", views.send_mail_api, name="send_mail"),              # POST -> send mail

    path('api/', include(router.urls)),

]

Contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    message = models.TextField()
    file = models.FileField(upload_to='uploads/', null=True, blank=True)  # فیلد فایل اختیاری
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Contact/forms.py
from django import forms
from .models import Contact  # مدل Contact که قبلاً تعریف کرده‌اید


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message', 'file']

About/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page
from rest_framework.viewsets import ModelViewSet

from Product.models import Product
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity
from .models import AboutUs, FAQ
from .serializers import AboutUsSerializer, FAQSerializer


@cache_page(60 * 15)
def about(request):
    current_language = get_language()
    is_bidi = get_language_bidi()
    aboutUs = AboutUs.objects.first()
    faq = FAQ.objects.all()
    products = Product.objects.all()

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'about.html', {'LANGUAGE_CODE': current_language,
                                          'LANGUAGE_BIDI': is_bidi,
                                          'About': aboutUs,
                                          'FAQ': faq,
                                          'Products': products,
                                          'activity_log_id': log.id,
                                          })


# _____________________________ Class Based Views for developing API ________________________________


class AboutUsView(ModelViewSet):
    queryset = AboutUs.objects.all()
    serializer_class = AboutUsSerializer


class FAQView(ModelViewSet):
    queryset = FAQ.objects.all()
    serializer_class = FAQSerializer

Blog/views.py
from django.db.models import Q
from django.utils.translation import get_language
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from rest_framework.generics import get_object_or_404
from About.models import AboutUs
from Blog.models import BlogPost
from Blog.serializers import BlogPostSerializer
from Product.models import Product


# لیست مقالات
class BlogPostListView(ListView):
    model = BlogPost
    template_name = "blogs.html"
    context_object_name = "blog_posts"
    paginate_by = 10  # تعداد مقالات در هر صفحه

    def get_queryset(self):
        queryset = BlogPost.objects.all().order_by("-published_date")
        filters = Q()
        author = self.request.GET.get("author")
        search = self.request.GET.get("search")

        if author:
            filters &= Q(author__username__icontains=author)
        if search:
            filters &= Q(title__icontains=search)

        return queryset.filter(filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_posts'] = BlogPost.objects.count()  # تعداد کل مقالات
        context['About'] = AboutUs.objects.first()
        context['products'] = Product.objects.all()

        return context


# جزئیات مقاله
class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = "blogpost.html"
    context_object_name = "blog_post"

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(BlogPost, id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_language'] = get_language()  # زبان جاری را اضافه می‌کنیم

        page_title = self.get_page_title()  # عنوان صفحه
        page_content = self.get_page_content()  # توصیف صفحه
        page_image = self.get_page_image()

        meta_title = self.get_meta_title()  # عنوان صفحه
        meta_description = self.get_meta_description()  # توصیف صفحه
        meta_keywords = self.get_meta_keywords()  # کلمات کلیدی
        canonical_url = self.request.build_absolute_uri(self.request.path)

        context['page_title'] = page_title
        context['page_content'] = page_content
        context['page_image'] = page_image

        context['meta_title'] = meta_title
        context['meta_description'] = meta_description
        context['meta_keywords'] = meta_keywords
        context['canonical_url'] = canonical_url

        return context

    def get_page_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.title

    def get_page_content(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.content  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_page_image(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.image  # اگر مقاله دسته‌بندی‌ها داشته باشد

    def get_meta_title(self):
        # شما می‌توانید عنوان صفحه را بر اساس عنوان مقاله بسازید
        blog_post = self.get_object()
        return blog_post.meta_title

    def get_meta_description(self):
        # توصیف صفحه می‌تواند از محتوای مقاله گرفته شود
        blog_post = self.get_object()
        return blog_post.meta_description  # یا هر فیلدی که توصیف کوتاهی از مقاله باشد

    def get_meta_keywords(self):
        # کلمات کلیدی می‌تواند بر اساس دسته‌بندی یا برچسب‌های مقاله باشد
        blog_post = self.get_object()
        return blog_post.meta_keywords  # اگر مقاله دسته‌بندی‌ها داشته باشد


class BlogPostViewSet(viewsets.ModelViewSet):
    queryset = BlogPost.objects.all().order_by('-published_date')  # لیست مقالات مرتب‌شده بر اساس تاریخ انتشار
    serializer_class = BlogPostSerializer

Contact/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page
from django.core.mail import EmailMessage
from rest_framework.response import Response
from rest_framework.views import APIView

from About.models import AboutUs
from Contact.forms import ContactForm
from Product.models import Product
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity


@cache_page(60 * 15)
def contact(request):
    current_language = get_language()
    is_bidi = get_language_bidi()
    aboutUs = AboutUs.objects.first()
    products = Product.objects.all()

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'contact.html', {'LANGUAGE_CODE': current_language,
                                            'LANGUAGE_BIDI': is_bidi,
                                            'About': aboutUs,
                                            'Products': products,
                                            'activity_log_id': log.id,

                                            })


class EmailView(APIView):
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.data, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            file = form.cleaned_data.get('file')

            email_subject = f"Message from {name}"
            email_body = f"Name: {name}\nPhone: {phone}\nEmail: {email}\n\nMessage:\n{message}"

            email_message = EmailMessage(
                email_subject,
                email_body,
                'customer@phoenixfamily.co',  # فرستنده
                ['info@phoenixfamily.co']  # گیرنده
            )

            if file:
                email_message.attach(file.name, file.read(), file.content_type)

            try:
                # Send the email
                email_message.send()
                return Response({"message": "Email successfully sent"}, status=200)
            except Exception as e:
                # Handle errors while sending the email
                return Response({"error": f"Error sending email: {str(e)}"}, status=500)

        return Response({"error": form.errors}, status=400)

Home/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi

from About.models import AboutUs
from Product.models import Product
from User.views import get_or_create_temporary_user, log_user_activity, save_user_device_info
from .serializers import ContentSerializer, FeaturesSerializer, VisionSerializer
from .models import Content, Vision, Features
from rest_framework import viewsets


def home(request):
    current_language = get_language()
    is_bidi = get_language_bidi()
    content = Content.objects.all()
    vision = Vision.objects.all()
    features = Features.objects.all()
    about = AboutUs.objects.first()
    products = Product.objects.all()

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'home.html',
                  {'LANGUAGE_CODE': current_language,
                   'LANGUAGE_BIDI': is_bidi,
                   'Content': content,
                   'Vision': vision,
                   'Features': features,
                   'About': about,
                   'Products': products,
                   'activity_log_id': log.id,

                   },
                  )


# _____________________________ Class Based Views for developing API ________________________________

class ContentView(viewsets.ModelViewSet):
    queryset = Content.objects.all()
    serializer_class = ContentSerializer


class VisionView(viewsets.ModelViewSet):
    queryset = Vision.objects.all()
    serializer_class = VisionSerializer


class FeaturesView(viewsets.ModelViewSet):
    queryset = Features.objects.all()
    serializer_class = FeaturesSerializer

Product/views.py
from django.shortcuts import render
from django.utils.translation import get_language, get_language_bidi
from django.views.decorators.cache import cache_page
from rest_framework.viewsets import ModelViewSet

from About.models import AboutUs
from User.views import get_or_create_temporary_user, save_user_device_info, log_user_activity
from .models import Product, Features
from .serializers import ProductSerializer, FeaturesSerializer


@cache_page(60 * 15)
def products(request, pk):
    current_language = get_language()
    is_bidi = get_language_bidi()
    aboutUs = AboutUs.objects.first()
    product = Product.objects.all()
    item = Product.objects.get(id=pk)
    features = Features.objects.filter(product_id=pk)

    if request.user.is_authenticated:
        user = request.user
    else:
        user = get_or_create_temporary_user(request)
        save_user_device_info(request, user)

    log = log_user_activity(request, request.build_absolute_uri(), user)

    return render(request, 'products.html', {'LANGUAGE_CODE': current_language,
                                             'LANGUAGE_BIDI': is_bidi,
                                             'About': aboutUs,
                                             'Products': product,
                                             'Item': item,
                                             'Features': features,
                                             'activity_log_id': log.id,

                                             })


# _____________________________ Class Based Views for developing API ________________________________

class ProductView(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class FeaturesView(ModelViewSet):
    queryset = Features.objects.all()
    serializer_class = FeaturesSerializer

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ seo_title|default:"PhoenixFamily" }}</title>
    <meta name="description" content="{{ seo_description }}">
    <meta name="keywords" content="{{ seo_keywords }}">
    <meta name="robots" content="index, follow">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <link rel="canonical" href="{{ canonical_url|default:request.build_absolute_uri }}">
    <meta property="og:title" content="{{ seo_title|default:"PhoenixFamily" }}">
    <meta property="og:description" content="{{ seo_description }}">
    <meta property="og:image" content="{% static 'images/logo.png' %}">
    <meta property="og:url" content="{{ canonical_url|default:request.build_absolute_uri }}">
    <meta name="twitter:title" content="{{ seo_title|default:"PhoenixFamily" }}">
    <meta name="twitter:description" content="{{ seo_description }}">
    <meta name="twitter:image" content="{% static 'images/logo.png' %}">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/4a2a05a158.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>

    </style>

    <script type="application/ld+json">
        {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "PhoenixFamily",
        "url": "https://phoenixfamily.co",
        "logo": "https://phoenixfamily.co/media/images/logo.png"
        }
    </script>


    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WTMWZHKD23"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-WTMWZHKD23');
    </script>

    <!-- Google Tag Manager -->
    <script>(function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start':
                new Date().getTime(), event: 'gtm.js'
        });
        let f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l !== 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-KG2BJLP7');</script>
    <!-- End Google Tag Manager -->

</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg shadow-sm">
        <div class="container">

            <a class="navbar-brand" href="//phoenixfamily.co">
                <img src="{{ About.logo.url }}" alt="{% trans 'Logo' %}" class="d-inline-block align-text-top">
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
                <i class="fa-solid fa-bars custom-toggler"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link active"
                                            href="{% url 'home:home-view' %}">{% trans "Home" %}</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-expanded="false">{% trans "Products" %}</a>
                        <ul class="dropdown-menu">
                            {% for x in Products %}
                                <li><a class="dropdown-item"
                                       href="{% url 'products:product-view' x.id %}">{{ x.name|capfirst }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link"
                                            href="{% url 'contact:contact-view' %}">{% trans "Contact Us" %}</a>
                    </li>
                    <li class="nav-item"><a class="nav-link"
                                            href="{% url 'about:about-view' %}">{% trans "About Us" %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blogs:blog-view' %}">{% trans "Blogs" %}</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:login_view' %}">{% trans "Login" %}</a>
                    </li>

                </ul>
                <!-- دکمه تغییر تم -->
                <div class="ms-3 d-flex align-items-center">
                    <i class="fas fa-sun" id="sun-icon"></i>
                    <div class="ms-2 form-check form-switch">
                        <label for="theme-switch"></label>
                        <input class="form-check-input" type="checkbox" role="switch" id="theme-switch"
                               aria-label="Toggle theme"/>
                    </div>
                    <i class="fas fa-moon" id="moon-icon"></i>
                </div>

                <!-- فرم تغییر زبان -->
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <label>
                        <select name="language" class="form-select form-select-sm w-auto"
                                onchange="this.form.submit()" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                        selected{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                    </label>
                </form>

            </div>
        </div>
    </nav>
</header>

<!-- محتوای متغیر -->
<div id="content">
    {% block content %}
    {% endblock %}
</div>

<footer>
    <div class="container py-4">
        {% block footer %}


        {% endblock %}

        <!-- کپی‌رایت -->
        <div class="row mt-4">
            <div class="col-12 text-center">
                <p class="mb-0 copyright">
                    &copy; 2024 PhoenixFamily. {% trans "All rights reserved." %}
                </p>
            </div>
        </div>
    </div>
</footer>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const themeSwitch = document.getElementById("theme-switch");
        const sunIcon = document.getElementById("sun-icon");
        const moonIcon = document.getElementById("moon-icon");

        const isDark = localStorage.getItem("theme") === "dark";

        // تغییر تم و نمایش آیکون‌ها
        if (isDark) {
            document.body.classList.add("dark-mode");
            sunIcon.style.display = "none";
            moonIcon.style.display = "inline";
        } else {
            document.body.classList.remove("dark-mode");
            sunIcon.style.display = "inline";
            moonIcon.style.display = "none";
        }

        themeSwitch.checked = isDark;

        themeSwitch.addEventListener("change", function () {
            const isDark = this.checked;
            document.body.classList.toggle("dark-mode", isDark);

            if (isDark) {
                sunIcon.style.display = "none";
                moonIcon.style.display = "inline";
            } else {
                sunIcon.style.display = "inline";
                moonIcon.style.display = "none";
            }

            localStorage.setItem("theme", isDark ? "dark" : "light");
        });
        console.log(localStorage.getItem("theme"));
        console.log(document.documentElement.classList);

    });
</script>

</body>

<!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KG2BJLP7"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->

</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


    <section class="swiper-section py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-card rounded p-4 shadow">
                        <h3 class="mb-3 text-center fw-bold">{% trans "Welcome" %}</h3>
                        <p class="text-center text-muted small">{% trans "Please Sign In to Your Account" %}</p>

                        <form method="post" class="mt-4">
                            {% csrf_token %}

                            <div class="mb-3">
                                <label class="form-label" for="id_username">{% trans 'Username' %}</label>
                                <input type="text" id="id_username" class="form-control"
                                       placeholder="{% trans 'username' %}" required>
                            </div>

                            <div class="mb-3 position-relative">
                                <label class="form-label" for="password">{% trans 'Password' %}</label>
                                <input type="password" id="password" class="form-control"
                                       placeholder="{% trans 'password' %}" required>
                                <i class="fas fa-eye position-absolute top-50 {% if LANGUAGE_BIDI %}start-0{% else %}end-0{% endif %} translate-middle-y px-3 mt-3"
                                   id="togglePassword"></i>
                            </div>

                            <div class="text-end mb-3">
                                <a href="#" class="small">{% trans 'Forgot password?' %}</a>
                            </div>

                            <div class="d-grid">
                                <button id="submit" class="btn btn-cta btn-lg"
                                        type="submit">{% trans "Login" %}</button>


                            </div>
                        </form>

                        <p class="mt-4 text-center small">
                            {% trans "Don't have an account?" %}
                            <a href="{% url 'user:register_view' %}">{% trans "Register" %}</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const submit = document.getElementById('submit');
            const togglePassword = document.getElementById("togglePassword");

            togglePassword.addEventListener("click", () => {
                const passwordField = document.getElementById("password");
                const type = passwordField.getAttribute("type") === "password" ? "text" : "password";
                passwordField.setAttribute("type", type);
                togglePassword.classList.toggle("fa-eye-slash");
            });

            submit.addEventListener("click", async (e) => {
                e.preventDefault();
                const username = document.getElementById("id_username").value;  // ← درست شد
                const password = document.getElementById("password").value;

                const response = await fetch("{% url 'user:login' %}", {
                    method: "POST",
                    headers: {'Content-Type': "application/json"},
                    body: JSON.stringify({username, password})
                });

                if (response.ok) {
                    const userData = await response.json();
                    if (userData.user.is_staff) {

                    } else if (userData.user.is_admin) {

                    } else {
                        // کاربر عادی → اینباکس
                        location.assign(`{% url 'webmail:inbox_view' %}`);
                    }
                } else {
                    const error = await response.json();
                    alert(error.error || "ورود ناموفق. لطفاً دوباره تلاش کنید.");
                }
            });

        });
    </script>



{% endblock %}


{% block footer %}
    <div class="row align-items-center">
        <!-- لوگوی شرکت -->
        <div class="col-md-4 text-center mb-3 mb-md-0">
            <a href="//phoenixfamily.co">
                <img src="{{ About.logo.url }}" alt="{{ About.name }}" class="img-fluid" style="max-width: 150px;">
            </a>
        </div>

        <!-- اطلاعات تماس -->
        <div class="col-md-4 text-center mb-3 mb-md-0">
            <h6 class="mb-2">{% trans "Contact Us" %}</h6>
            <p class="mb-1">
                <i class="fas fa-phone-alt contact-icon  me-2"></i>{% trans "Phone" %}: {{ About.number }}
            </p>
            <p class="mb-0">
                <i class="fas fa-envelope contact-icon me-2"></i>{% trans "Email" %}: {{ About.email }}
            </p>
        </div>

        <!-- شبکه‌های اجتماعی -->
        <div class="col-md-4 text-center right">
            <h6 class="mb-2">{% trans "Follow Us" %}</h6>
            <div class="social-icons">
                <a href="{{ About.instagram }}" class="me-3"><i class="fab fa-instagram fa-lg"></i></a>
                <a href="{{ About.telegram }}" class="me-3"><i class="fab fa-telegram fa-lg"></i></a>
                <a href="{{ About.whatsApp }}" class="me-3"><i class="fab fa-whatsapp fa-lg"></i></a>
                <a href="{{ About.linkedin }}"><i class="fa-brands fa-linkedin fa-lg"></i></a>
            </div>
        </div>
    </div>

{% endblock %}